version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          command: cat publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: thesellsword-machineuser/helm-charts
            - GITHUB_PAGES_BRANCH: master
      - run:
          name: Verify
          command: |
            alias helm=/tmp/helm/bin/linux-amd64/helm
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              helm repo add thesellsword https://thesellsword-machineuser.github.io/helm-charts
              helm repo update
              helm repo list
              helm inspect thesellsword/kubetemplates
            fi
